### ISSUE TITLE
Frontend build - powergrid

### ISSUE THREAD

**Issue by lionslair** [realodix/urlhub#888]
**Describe the bug**
Seems to be an issue building the frontend. Appears tired to the powergrid components.

**To Reproduce**
1. npm install
2.  npm run dev

**Expected behavior**
Frontend builds

**Actual behavoir**

```bash
╰─$ npm run dev 

> dev
> npm run development


> development
> mix


✖ Mix
  Compiled with some errors in 1.37s

ERROR in ./resources/css/main.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module './vendor/power-components/livewire-powergrid/tailwind.config.js'
Require stack:
- /home/nathanr/Code/urlhub/tailwind.config.js
- /home/nathanr/Code/urlhub/node_modules/tailwindcss/lib/lib/setupTrackingContext.js
- /home/nathanr/Code/urlhub/node_modules/tailwindcss/lib/plugin.js
- /home/nathanr/Code/urlhub/node_modules/tailwindcss/lib/index.js
- /home/nathanr/Code/urlhub/webpack.mix.js
- /home/nathanr/Code/urlhub/node_modules/laravel-mix/setup/webpack.config.js
- /home/nathanr/Code/urlhub/node_modules/webpack-cli/lib/webpack-cli.js
- /home/nathanr/Code/urlhub/node_modules/webpack-cli/lib/bootstrap.js
- /home/nathanr/Code/urlhub/node_modules/webpack-cli/bin/cli.js
- /home/nathanr/Code/urlhub/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/nathanr/Code/urlhub/tailwind.config.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at getTailwindConfig (/home/nathanr/Code/urlhub/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:68:53)
    at /home/nathanr/Code/urlhub/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:97:92
    at /home/nathanr/Code/urlhub/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
    at plugins (/home/nathanr/Code/urlhub/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/home/nathanr/Code/urlhub/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/nathanr/Code/urlhub/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/nathanr/Code/urlhub/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/home/nathanr/Code/urlhub/node_modules/postcss/lib/lazy-result.js:206:17)
    at processResult (/home/nathanr/Code/urlhub/node_modules/webpack/lib/NormalModule.js:760:19)
    at /home/nathanr/Code/urlhub/node_modules/webpack/lib/NormalModule.js:862:5
    at /home/nathanr/Code/urlhub/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /home/nathanr/Code/urlhub/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/home/nathanr/Code/urlhub/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/nathanr/Code/urlhub/node_modules/postcss-loader/dist/index.js:142:7)

```

**Screenshots**

![image](https://user-images.githubusercontent.com/832259/230709000-523f797b-121d-44fd-9f48-d69777b9e569.png)

![image](https://user-images.githubusercontent.com/832259/230709029-608d1b40-224a-4529-8f87-15c86ed92ff9.png)

**Additional Information**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by realodix** [comment]
PowerGrid has been upgraded to version 4 (https://github.com/realodix/urlhub/pull/887)

```diff
"require": {
-    "power-components/livewire-powergrid": "^3.7",
+    "power-components/livewire-powergrid": "^4.0",
},
```

```sh
composer u
```
